version: '3.5'

services:
  zookeeper:
    image: strimzi/kafka:0.11.3-kafka-2.1.0
    command: [
      "sh", "-c",
      "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs
    networks:
      - kafkastreams-network
  kafka:
    image: strimzi/kafka:0.11.3-kafka-2.1.0
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT} --override num.partitions=$${KAFKA_NUM_PARTITIONS}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_NUM_PARTITIONS: 1
    networks:
      - kafkastreams-network
  mongodb-employee-profile:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - kafkastreams-network
  vacation-producer:
    image: rrojas/vacation-producer:0.1
    build:
      context: kafka-employee-vacation-request
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - zookeeper
      - kafka
      - vacation-enricher
    networks:
      - kafkastreams-network
  vacation-enricher:
    image: rrojas/vacation-enricher:0.1
    build:
      context: kafka-vacation-enricher
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      QUARKUS_KAFKA_STREAMS_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - zookeeper
      - kafka
    networks:
      - kafkastreams-network
  employee-profile:
    image: rrojas/employee-profile:0.1
    build:
      context: kafka-employee-profile-service
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      QUARKUS_KAFKA_STREAMS_BOOTSTRAP_SERVERS: kafka:9092
      QUARKUS_MONGODB_CONNECTION_STRING: mongodb://admin:root@mongodb-employee-profile:27017
    depends_on:
      - zookeeper
      - kafka
      - mongodb-employee-profile
    networks:
      - kafkastreams-network
networks:
  kafkastreams-network:
    name: ks